{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "muthur-collector.fullname" . }}-secret
  labels:
    {{- include "muthur-collector.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "muthur-collector.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: CENTRAL_AGENT_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretPath }}
        property: central-agent-url
    - secretKey: CENTRAL_AGENT_TOKEN
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretPath }}
        property: central-agent-token
{{- end }}
{{- if and .Values.devSecrets.enabled (not .Values.externalSecrets.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muthur-collector.fullname" . }}-secret
  labels:
    {{- include "muthur-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  CENTRAL_AGENT_URL: {{ .Values.devSecrets.centralAgentUrl | quote }}
  CENTRAL_AGENT_TOKEN: {{ .Values.devSecrets.centralAgentToken | quote }}
{{- end }}
