// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/alert.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Brain_Ingest_FullMethodName        = "/monitoring.v1.Brain/Ingest"
	Brain_BootstrapCert_FullMethodName = "/monitoring.v1.Brain/BootstrapCert"
	Brain_SignCSR_FullMethodName       = "/monitoring.v1.Brain/SignCSR"
)

// BrainClient is the client API for Brain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Brain is the central service collectors talk to over mTLS. Replay protection
// (timestamp + nonce) is carried via gRPC metadata, not message fields, so the
// wire shape stays a pure data contract.
type BrainClient interface {
	// Ingest accepts an alert payload pushed by a collector. Identity comes
	// from the verified client cert (peer.Peer), not from the request body —
	// payload.cluster_id is cross-checked against the cert's cluster_id.
	Ingest(ctx context.Context, in *AlertPayload, opts ...grpc.CallOption) (*IngestResponse, error)
	// BootstrapCert issues the first leaf cert to a collector that has no
	// prior credentials. Authenticated by a one-time bootstrap token in the
	// request body; the listener accepts cert-less handshakes for this RPC.
	BootstrapCert(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
	// SignCSR renews a collector's leaf cert. Authenticated by the existing
	// client cert presented during the mTLS handshake; the CSR contributes
	// only the new public key.
	SignCSR(ctx context.Context, in *SignCSRRequest, opts ...grpc.CallOption) (*SignCSRResponse, error)
}

type brainClient struct {
	cc grpc.ClientConnInterface
}

func NewBrainClient(cc grpc.ClientConnInterface) BrainClient {
	return &brainClient{cc}
}

func (c *brainClient) Ingest(ctx context.Context, in *AlertPayload, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, Brain_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainClient) BootstrapCert(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, Brain_BootstrapCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainClient) SignCSR(ctx context.Context, in *SignCSRRequest, opts ...grpc.CallOption) (*SignCSRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignCSRResponse)
	err := c.cc.Invoke(ctx, Brain_SignCSR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrainServer is the server API for Brain service.
// All implementations must embed UnimplementedBrainServer
// for forward compatibility.
//
// Brain is the central service collectors talk to over mTLS. Replay protection
// (timestamp + nonce) is carried via gRPC metadata, not message fields, so the
// wire shape stays a pure data contract.
type BrainServer interface {
	// Ingest accepts an alert payload pushed by a collector. Identity comes
	// from the verified client cert (peer.Peer), not from the request body —
	// payload.cluster_id is cross-checked against the cert's cluster_id.
	Ingest(context.Context, *AlertPayload) (*IngestResponse, error)
	// BootstrapCert issues the first leaf cert to a collector that has no
	// prior credentials. Authenticated by a one-time bootstrap token in the
	// request body; the listener accepts cert-less handshakes for this RPC.
	BootstrapCert(context.Context, *BootstrapRequest) (*BootstrapResponse, error)
	// SignCSR renews a collector's leaf cert. Authenticated by the existing
	// client cert presented during the mTLS handshake; the CSR contributes
	// only the new public key.
	SignCSR(context.Context, *SignCSRRequest) (*SignCSRResponse, error)
	mustEmbedUnimplementedBrainServer()
}

// UnimplementedBrainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrainServer struct{}

func (UnimplementedBrainServer) Ingest(context.Context, *AlertPayload) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedBrainServer) BootstrapCert(context.Context, *BootstrapRequest) (*BootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BootstrapCert not implemented")
}
func (UnimplementedBrainServer) SignCSR(context.Context, *SignCSRRequest) (*SignCSRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignCSR not implemented")
}
func (UnimplementedBrainServer) mustEmbedUnimplementedBrainServer() {}
func (UnimplementedBrainServer) testEmbeddedByValue()               {}

// UnsafeBrainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrainServer will
// result in compilation errors.
type UnsafeBrainServer interface {
	mustEmbedUnimplementedBrainServer()
}

func RegisterBrainServer(s grpc.ServiceRegistrar, srv BrainServer) {
	// If the following call panics, it indicates UnimplementedBrainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Brain_ServiceDesc, srv)
}

func _Brain_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Brain_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServer).Ingest(ctx, req.(*AlertPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brain_BootstrapCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServer).BootstrapCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Brain_BootstrapCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServer).BootstrapCert(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brain_SignCSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignCSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServer).SignCSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Brain_SignCSR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServer).SignCSR(ctx, req.(*SignCSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Brain_ServiceDesc is the grpc.ServiceDesc for Brain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Brain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.v1.Brain",
	HandlerType: (*BrainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _Brain_Ingest_Handler,
		},
		{
			MethodName: "BootstrapCert",
			Handler:    _Brain_BootstrapCert_Handler,
		},
		{
			MethodName: "SignCSR",
			Handler:    _Brain_SignCSR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/alert.proto",
}
