// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/alert.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterId         string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AlertName         string                 `protobuf:"bytes,2,opt,name=alert_name,json=alertName,proto3" json:"alert_name,omitempty"`
	Severity          string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // critical | warning | info
	Namespace         string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName           string                 `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	FiredAt           int64                  `protobuf:"varint,6,opt,name=fired_at,json=firedAt,proto3" json:"fired_at,omitempty"` // unix timestamp seconds
	Summary           string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Description       string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Target            *AlertTarget           `protobuf:"bytes,9,opt,name=target,proto3" json:"target,omitempty"`
	RedactedLogs      []string               `protobuf:"bytes,10,rep,name=redacted_logs,json=redactedLogs,proto3" json:"redacted_logs,omitempty"`
	Metrics           []*MetricSeries        `protobuf:"bytes,11,rep,name=metrics,proto3" json:"metrics,omitempty"`
	PodMetas          []*PodMeta             `protobuf:"bytes,12,rep,name=pod_metas,json=podMetas,proto3" json:"pod_metas,omitempty"`
	Labels            []*Label               `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty"`
	TotalLogLines     int32                  `protobuf:"varint,14,opt,name=total_log_lines,json=totalLogLines,proto3" json:"total_log_lines,omitempty"`
	RedactedLogLines  int32                  `protobuf:"varint,15,opt,name=redacted_log_lines,json=redactedLogLines,proto3" json:"redacted_log_lines,omitempty"`
	TotalReplacements int32                  `protobuf:"varint,16,opt,name=total_replacements,json=totalReplacements,proto3" json:"total_replacements,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AlertPayload) Reset() {
	*x = AlertPayload{}
	mi := &file_proto_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertPayload) ProtoMessage() {}

func (x *AlertPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertPayload.ProtoReflect.Descriptor instead.
func (*AlertPayload) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AlertPayload) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AlertPayload) GetAlertName() string {
	if x != nil {
		return x.AlertName
	}
	return ""
}

func (x *AlertPayload) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertPayload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AlertPayload) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AlertPayload) GetFiredAt() int64 {
	if x != nil {
		return x.FiredAt
	}
	return 0
}

func (x *AlertPayload) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AlertPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertPayload) GetTarget() *AlertTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AlertPayload) GetRedactedLogs() []string {
	if x != nil {
		return x.RedactedLogs
	}
	return nil
}

func (x *AlertPayload) GetMetrics() []*MetricSeries {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AlertPayload) GetPodMetas() []*PodMeta {
	if x != nil {
		return x.PodMetas
	}
	return nil
}

func (x *AlertPayload) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AlertPayload) GetTotalLogLines() int32 {
	if x != nil {
		return x.TotalLogLines
	}
	return 0
}

func (x *AlertPayload) GetRedactedLogLines() int32 {
	if x != nil {
		return x.RedactedLogLines
	}
	return 0
}

func (x *AlertPayload) GetTotalReplacements() int32 {
	if x != nil {
		return x.TotalReplacements
	}
	return 0
}

type AlertTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // pod | deployment | daemonset | node | pvc | namespace | unknown
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Deployment    string                 `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Daemonset     string                 `protobuf:"bytes,4,opt,name=daemonset,proto3" json:"daemonset,omitempty"`
	Node          string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Pvc           string                 `protobuf:"bytes,6,opt,name=pvc,proto3" json:"pvc,omitempty"`
	Namespace     string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResolvedPods  []string               `protobuf:"bytes,8,rep,name=resolved_pods,json=resolvedPods,proto3" json:"resolved_pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertTarget) Reset() {
	*x = AlertTarget{}
	mi := &file_proto_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertTarget) ProtoMessage() {}

func (x *AlertTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertTarget.ProtoReflect.Descriptor instead.
func (*AlertTarget) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AlertTarget) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AlertTarget) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AlertTarget) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *AlertTarget) GetDaemonset() string {
	if x != nil {
		return x.Daemonset
	}
	return ""
}

func (x *AlertTarget) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *AlertTarget) GetPvc() string {
	if x != nil {
		return x.Pvc
	}
	return ""
}

func (x *AlertTarget) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AlertTarget) GetResolvedPods() []string {
	if x != nil {
		return x.ResolvedPods
	}
	return nil
}

type MetricSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"` // bytes | percent | count | seconds
	Points        []*DataPoint           `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeries) Reset() {
	*x = MetricSeries{}
	mi := &file_proto_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeries) ProtoMessage() {}

func (x *MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeries.ProtoReflect.Descriptor instead.
func (*MetricSeries) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{2}
}

func (x *MetricSeries) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricSeries) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricSeries) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricSeries) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{3}
}

func (x *DataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PodMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,2,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	MemoryRequest string                 `protobuf:"bytes,3,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	CpuLimit      string                 `protobuf:"bytes,4,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	CpuRequest    string                 `protobuf:"bytes,5,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	NodeName      string                 `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	RestartCount  int32                  `protobuf:"varint,7,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	Phase         string                 `protobuf:"bytes,8,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodMeta) Reset() {
	*x = PodMeta{}
	mi := &file_proto_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodMeta) ProtoMessage() {}

func (x *PodMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodMeta.ProtoReflect.Descriptor instead.
func (*PodMeta) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{4}
}

func (x *PodMeta) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodMeta) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *PodMeta) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *PodMeta) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *PodMeta) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *PodMeta) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PodMeta) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *PodMeta) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{5}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_alert_proto protoreflect.FileDescriptor

const file_proto_alert_proto_rawDesc = "" +
	"\n" +
	"\x11proto/alert.proto\x12\rmonitoring.v1\"\xf0\x04\n" +
	"\fAlertPayload\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1d\n" +
	"\n" +
	"alert_name\x18\x02 \x01(\tR\talertName\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12\x19\n" +
	"\bfired_at\x18\x06 \x01(\x03R\afiredAt\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x122\n" +
	"\x06target\x18\t \x01(\v2\x1a.monitoring.v1.AlertTargetR\x06target\x12#\n" +
	"\rredacted_logs\x18\n" +
	" \x03(\tR\fredactedLogs\x125\n" +
	"\ametrics\x18\v \x03(\v2\x1b.monitoring.v1.MetricSeriesR\ametrics\x123\n" +
	"\tpod_metas\x18\f \x03(\v2\x16.monitoring.v1.PodMetaR\bpodMetas\x12,\n" +
	"\x06labels\x18\r \x03(\v2\x14.monitoring.v1.LabelR\x06labels\x12&\n" +
	"\x0ftotal_log_lines\x18\x0e \x01(\x05R\rtotalLogLines\x12,\n" +
	"\x12redacted_log_lines\x18\x0f \x01(\x05R\x10redactedLogLines\x12-\n" +
	"\x12total_replacements\x18\x10 \x01(\x05R\x11totalReplacements\"\xf0\x01\n" +
	"\vAlertTarget\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1e\n" +
	"\n" +
	"deployment\x18\x03 \x01(\tR\n" +
	"deployment\x12\x1c\n" +
	"\tdaemonset\x18\x04 \x01(\tR\tdaemonset\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\x12\x10\n" +
	"\x03pvc\x18\x06 \x01(\tR\x03pvc\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x12#\n" +
	"\rresolved_pods\x18\b \x03(\tR\fresolvedPods\"\x97\x01\n" +
	"\fMetricSeries\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x120\n" +
	"\x06points\x18\x04 \x03(\v2\x18.monitoring.v1.DataPointR\x06points\"?\n" +
	"\tDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x84\x02\n" +
	"\aPodMeta\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12!\n" +
	"\fmemory_limit\x18\x02 \x01(\tR\vmemoryLimit\x12%\n" +
	"\x0ememory_request\x18\x03 \x01(\tR\rmemoryRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x04 \x01(\tR\bcpuLimit\x12\x1f\n" +
	"\vcpu_request\x18\x05 \x01(\tR\n" +
	"cpuRequest\x12\x1b\n" +
	"\tnode_name\x18\x06 \x01(\tR\bnodeName\x12#\n" +
	"\rrestart_count\x18\a \x01(\x05R\frestartCount\x12\x14\n" +
	"\x05phase\x18\b \x01(\tR\x05phase\"1\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB6Z4github.com/VojtechPastyrik/muthur-collector/proto/v1b\x06proto3"

var (
	file_proto_alert_proto_rawDescOnce sync.Once
	file_proto_alert_proto_rawDescData []byte
)

func file_proto_alert_proto_rawDescGZIP() []byte {
	file_proto_alert_proto_rawDescOnce.Do(func() {
		file_proto_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)))
	})
	return file_proto_alert_proto_rawDescData
}

var file_proto_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_alert_proto_goTypes = []any{
	(*AlertPayload)(nil), // 0: monitoring.v1.AlertPayload
	(*AlertTarget)(nil),  // 1: monitoring.v1.AlertTarget
	(*MetricSeries)(nil), // 2: monitoring.v1.MetricSeries
	(*DataPoint)(nil),    // 3: monitoring.v1.DataPoint
	(*PodMeta)(nil),      // 4: monitoring.v1.PodMeta
	(*Label)(nil),        // 5: monitoring.v1.Label
}
var file_proto_alert_proto_depIdxs = []int32{
	1, // 0: monitoring.v1.AlertPayload.target:type_name -> monitoring.v1.AlertTarget
	2, // 1: monitoring.v1.AlertPayload.metrics:type_name -> monitoring.v1.MetricSeries
	4, // 2: monitoring.v1.AlertPayload.pod_metas:type_name -> monitoring.v1.PodMeta
	5, // 3: monitoring.v1.AlertPayload.labels:type_name -> monitoring.v1.Label
	3, // 4: monitoring.v1.MetricSeries.points:type_name -> monitoring.v1.DataPoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_alert_proto_init() }
func file_proto_alert_proto_init() {
	if File_proto_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_alert_proto_goTypes,
		DependencyIndexes: file_proto_alert_proto_depIdxs,
		MessageInfos:      file_proto_alert_proto_msgTypes,
	}.Build()
	File_proto_alert_proto = out.File
	file_proto_alert_proto_goTypes = nil
	file_proto_alert_proto_depIdxs = nil
}
